### ISSUE TITLE
Rebrand to Severus Scrape

### ISSUE THREAD

**Issue by jimmed** [jimmed/severus-scrape#6]
'scrapegoat' is already taken as a [package name on npm](https://npm.im/scrapegoat).

Need a better name!

**Comment by tasinet** [comment]
FTWindex
?

**Comment by tasinet** [comment]
Scrappydoo

**Comment by tasinet** [comment]
Xedni

**Comment by tasinet** [comment]
Smarchive

**Comment by jimmed** [comment]
`severus-scrape`
